# Generated by Django 4.2.3 on 2023-07-07 08:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("social", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="user",
        ),
    ]
